import * as functions from "./functions.js";

export type SystemeResults = {
	cch: ReturnType<typeof functions.calcule_cch>;
	caux_dist: ReturnType<typeof functions.calcule_caux_dist>;
	bch: ReturnType<typeof functions.calcule_bch>;
	rdim: ReturnType<typeof functions.calcule_rdim>;
	role: ReturnType<typeof functions.calcule_role>["role"];
	type_releve: ReturnType<typeof functions.calcule_role>["type_releve"];
	pch: ReturnType<typeof functions.calcule_pch>;
	pe: ReturnType<typeof functions.calcule_pe>;
	dht: ReturnType<typeof functions.calcule_dht>;
	t: ReturnType<typeof functions.calcule_t>;
	int: ReturnType<typeof functions.calcule_int>;
	i0: ReturnType<typeof functions.calcule_i0>;
	ich: ReturnType<typeof functions.calcule_ich>;
	rd: ReturnType<typeof functions.calcule_rd>;
	re: ReturnType<typeof functions.calcule_re>;
	rg: ReturnType<typeof functions.calcule_rg>;
	rr: ReturnType<typeof functions.calcule_rr>;
	fut_pac_hyb: ReturnType<typeof functions.calcule_fut_pac_hyb>;
	type_emission: ReturnType<typeof functions.calcule_type_emission>;
	pmfou: ReturnType<typeof functions.calcule_pmfou>;
	pmcons: ReturnType<typeof functions.calcule_pmcons>;
	pfou: ReturnType<typeof functions.calcule_pfou>;
	pcons: ReturnType<typeof functions.calcule_pcons>;
	p: ReturnType<typeof functions.calcule_p>;
	qp: ReturnType<typeof functions.calcule_qp>;
	tch: ReturnType<typeof functions.calcule_tch>;
	tch_dim: ReturnType<typeof functions.calcule_tch_dim>;
	tch_final: ReturnType<typeof functions.calcule_tch_final>;
	coeff_pond: ReturnType<typeof functions.calcule_coeff_pond>;
	coeff_pond_dim: ReturnType<typeof functions.calcule_coeff_pond_dim>;
	coeff_pond_final: ReturnType<typeof functions.calcule_coeff_pond_final>;
	ctch_1: ReturnType<typeof functions.calcule_ctch_1>;
	ctch_2: ReturnType<typeof functions.calcule_ctch_2>;
	cdim_ref: ReturnType<typeof functions.calcule_cdim_ref>;
	tcons: ReturnType<typeof functions.calcule_tcons>;
	prel: ReturnType<typeof functions.calcule_prel>;
	pn_combustion: ReturnType<typeof functions.calcule_pn_combustion>;
	pn_cascade: ReturnType<typeof functions.calcule_pn_cascade>;
	pcircem: ReturnType<typeof functions.calcule_pcircem>;
};
